[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iris-streamlit-mlops"
version = "0.1.0"
description = "Iris ML Project for Streamlit Deployment"

packages = ["app"]